public struct IdString {
  internal let value: PyString
  internal let hash: PyHash

  public static var __abs__: IdString { fatalError() }
  public static var __add__: IdString { fatalError() }
  public static var __all__: IdString { fatalError() }
  public static var __and__: IdString { fatalError() }
  public static var __annotations__: IdString { fatalError() }
  public static var __bool__: IdString { fatalError() }
  public static var __build_class__: IdString { fatalError() }
  public static var __builtins__: IdString { fatalError() }
  public static var __call__: IdString { fatalError() }
  public static var __class__: IdString { fatalError() }
  public static var __class_getitem__: IdString { fatalError() }
  public static var __classcell__: IdString { fatalError() }
  public static var __complex__: IdString { fatalError() }
  public static var __contains__: IdString { fatalError() }
  public static var __del__: IdString { fatalError() }
  public static var __delattr__: IdString { fatalError() }
  public static var __delitem__: IdString { fatalError() }
  public static var __dict__: IdString { fatalError() }
  public static var __dir__: IdString { fatalError() }
  public static var __divmod__: IdString { fatalError() }
  public static var __doc__: IdString { fatalError() }
  public static var __enter__: IdString { fatalError() }
  public static var __eq__: IdString { fatalError() }
  public static var __exit__: IdString { fatalError() }
  public static var __file__: IdString { fatalError() }
  public static var __float__: IdString { fatalError() }
  public static var __floordiv__: IdString { fatalError() }
  public static var __ge__: IdString { fatalError() }
  public static var __get__: IdString { fatalError() }
  public static var __getattr__: IdString { fatalError() }
  public static var __getattribute__: IdString { fatalError() }
  public static var __getitem__: IdString { fatalError() }
  public static var __gt__: IdString { fatalError() }
  public static var __hash__: IdString { fatalError() }
  public static var __iadd__: IdString { fatalError() }
  public static var __iand__: IdString { fatalError() }
  public static var __idivmod__: IdString { fatalError() }
  public static var __ifloordiv__: IdString { fatalError() }
  public static var __ilshift__: IdString { fatalError() }
  public static var __imatmul__: IdString { fatalError() }
  public static var __imod__: IdString { fatalError() }
  public static var __import__: IdString { fatalError() }
  public static var __imul__: IdString { fatalError() }
  public static var __index__: IdString { fatalError() }
  public static var __init__: IdString { fatalError() }
  public static var __init_subclass__: IdString { fatalError() }
  public static var __instancecheck__: IdString { fatalError() }
  public static var __int__: IdString { fatalError() }
  public static var __invert__: IdString { fatalError() }
  public static var __ior__: IdString { fatalError() }
  public static var __ipow__: IdString { fatalError() }
  public static var __irshift__: IdString { fatalError() }
  public static var __isabstractmethod__: IdString { fatalError() }
  public static var __isub__: IdString { fatalError() }
  public static var __iter__: IdString { fatalError() }
  public static var __itruediv__: IdString { fatalError() }
  public static var __ixor__: IdString { fatalError() }
  public static var __le__: IdString { fatalError() }
  public static var __len__: IdString { fatalError() }
  public static var __loader__: IdString { fatalError() }
  public static var __lshift__: IdString { fatalError() }
  public static var __lt__: IdString { fatalError() }
  public static var __matmul__: IdString { fatalError() }
  public static var __missing__: IdString { fatalError() }
  public static var __mod__: IdString { fatalError() }
  public static var __module__: IdString { fatalError() }
  public static var __mul__: IdString { fatalError() }
  public static var __name__: IdString { fatalError() }
  public static var __ne__: IdString { fatalError() }
  public static var __neg__: IdString { fatalError() }
  public static var __new__: IdString { fatalError() }
  public static var __next__: IdString { fatalError() }
  public static var __or__: IdString { fatalError() }
  public static var __package__: IdString { fatalError() }
  public static var __path__: IdString { fatalError() }
  public static var __pos__: IdString { fatalError() }
  public static var __pow__: IdString { fatalError() }
  public static var __prepare__: IdString { fatalError() }
  public static var __qualname__: IdString { fatalError() }
  public static var __radd__: IdString { fatalError() }
  public static var __rand__: IdString { fatalError() }
  public static var __rdivmod__: IdString { fatalError() }
  public static var __repr__: IdString { fatalError() }
  public static var __reversed__: IdString { fatalError() }
  public static var __rfloordiv__: IdString { fatalError() }
  public static var __rlshift__: IdString { fatalError() }
  public static var __rmatmul__: IdString { fatalError() }
  public static var __rmod__: IdString { fatalError() }
  public static var __rmul__: IdString { fatalError() }
  public static var __ror__: IdString { fatalError() }
  public static var __round__: IdString { fatalError() }
  public static var __rpow__: IdString { fatalError() }
  public static var __rrshift__: IdString { fatalError() }
  public static var __rshift__: IdString { fatalError() }
  public static var __rsub__: IdString { fatalError() }
  public static var __rtruediv__: IdString { fatalError() }
  public static var __rxor__: IdString { fatalError() }
  public static var __set__: IdString { fatalError() }
  public static var __set_name__: IdString { fatalError() }
  public static var __setattr__: IdString { fatalError() }
  public static var __setitem__: IdString { fatalError() }
  public static var __spec__: IdString { fatalError() }
  public static var __str__: IdString { fatalError() }
  public static var __sub__: IdString { fatalError() }
  public static var __subclasscheck__: IdString { fatalError() }
  public static var __truediv__: IdString { fatalError() }
  public static var __trunc__: IdString { fatalError() }
  public static var __warningregistry__: IdString { fatalError() }
  public static var __xor__: IdString { fatalError() }
  public static var _find_and_load: IdString { fatalError() }
  public static var _handle_fromlist: IdString { fatalError() }
  public static var builtins: IdString { fatalError() }
  public static var encoding: IdString { fatalError() }
  public static var keys: IdString { fatalError() }
  public static var metaclass: IdString { fatalError() }
  public static var mro: IdString { fatalError() }
  public static var name: IdString { fatalError() }
  public static var object: IdString { fatalError() }
  public static var origin: IdString { fatalError() }
}
