#if !canImport(ObjectiveC)
import XCTest

extension Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Tests = [
        ("test_common_block", test_common_block),
        ("test_common_block_recursive", test_common_block_recursive),
        ("test_common_documents", test_common_documents),
        ("test_common_join", test_common_join),
        ("test_common_spread", test_common_spread),
        ("test_common_stack", test_common_stack),
        ("test_ctors", test_ctors),
        ("test_lyrics_part", test_lyrics_part),
        ("test_lyrics_song", test_lyrics_song),
        ("test_nest_recursive", test_nest_recursive),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Tests.__allTests__Tests),
    ]
}
#endif
