// In CPython:
// Objects -> exceptions.c
// Lib->test->exception_hierarchy.txt <-- this is amazing
// https://docs.python.org/3.7/c-api/exceptions.html

// sourcery: pywarningtype = Warning
internal class PyWarning: PyException {

  override internal class var doc: String {
    return "Base class for warning categories."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = UserWarning
internal final class PyUserWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings generated by user code."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = DeprecationWarning
internal final class PyDeprecationWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about deprecated features."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = PendingDeprecationWarning
internal final class PyPendingDeprecationWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about features which will be deprecated " +
    "in the future."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = SyntaxWarning
internal final class PySyntaxWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about dubious syntax."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = RuntimeWarning
internal final class PyRuntimeWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about dubious runtime behavior."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = FutureWarning
internal final class PyFutureWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about constructs that will change " +
    "semantically in the future."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = ImportWarning
internal final class PyImportWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about probable mistakes in module imports"
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = UnicodeWarning
internal final class PyUnicodeWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about Unicode related problems, " +
    "mostly related to conversion problems."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = BytesWarning
internal final class PyBytesWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about bytes and buffer related problems, " +
    "mostly related to conversion from str or comparing to str."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}

// sourcery: pywarningtype = ResourceWarning
internal final class PyResourceWarning: PyWarning {

  override internal class var doc: String {
    return "Base class for warnings about resource usage."
  }

  // MARK: - Dict

  // sourcery: pyproperty = __dict__
  override internal func dict() -> Attributes {
    return self._attributes
  }
}
