import Foundation

internal func emitHeader(sourceFile: URL, command: String) {
  let filename = sourceFile.lastPathComponent

  print("""
// This file was auto-generated by Elsa from '\(filename)' using '\(command)' command.
// DO NOT EDIT!

""")
}
