// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import Foundation

internal func emitHeader(sourceFile: URL, command: String) {
  let filename = sourceFile.lastPathComponent

  print("""
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

""")

  print("""
// This file was auto-generated by Elsa from '\(filename)' using '\(command)' command.
// DO NOT EDIT!

""")
}
