import XCTest
import BigInt

// swiftlint:disable function_parameter_count

// Basically all of the code that does not need to be regenerated by Node.
extension NodeTests {

  // MARK: - Unary operations

  internal func plusTest(value: String,
                         expecting: String,
                         file: StaticString = #file,
                         line: UInt = #line) {
    self.unaryOp(
      value: value,
      expecting: expecting,
      op: { +$0 },
      file: file,
      line: line
    )
  }

  internal func minusTest(value: String,
                          expecting: String,
                          file: StaticString = #file,
                          line: UInt = #line) {
    self.unaryOp(
      value: value,
      expecting: expecting,
      op: { -$0 },
      file: file,
      line: line
    )
  }

  internal func invertTest(value: String,
                           expecting: String,
                           file: StaticString = #file,
                           line: UInt = #line) {
    self.unaryOp(
      value: value,
      expecting: expecting,
      op: { ~$0 },
      file: file,
      line: line
    )
  }

  internal typealias UnaryOperation = (BigInt) -> BigInt

  private func unaryOp(value valueString: String,
                       expecting expectedString: String,
                       op: UnaryOperation,
                       file: StaticString,
                       line: UInt) {
    guard let value = self.create(string: valueString, radix: 10) else {
      XCTFail("Unable to parse value", file: file, line: line)
      return
    }

    guard let expected = self.create(string: expectedString, radix: 10) else {
      XCTFail("Unable to parse expected", file: file, line: line)
      return
    }

    let result = op(value)
    XCTAssertEqual(result, expected, file: file, line: line)
  }

  // MARK: - Binary operations

  internal func addTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 + $1 },
      inoutOp: { $0 += $1 },
      file: file,
      line: line
    )
  }

  internal func subTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 - $1 },
      inoutOp: { $0 -= $1 },
      file: file,
      line: line
    )
  }

  internal func mulTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 * $1 },
      inoutOp: { $0 *= $1 },
      file: file,
      line: line
    )
  }

  internal func divTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 / $1 },
      inoutOp: { $0 /= $1 },
      file: file,
      line: line
    )
  }

  internal func modTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 % $1 },
      inoutOp: { $0 %= $1 },
      file: file,
      line: line
    )
  }

  internal func andTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 & $1 },
      inoutOp: { $0 &= $1 },
      file: file,
      line: line
    )
  }

  internal func orTest(lhs: String,
                       rhs: String,
                       expecting: String,
                       file: StaticString = #file,
                       line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 | $1 },
      inoutOp: { $0 |= $1 },
      file: file,
      line: line
    )
  }

  internal func xorTest(lhs: String,
                        rhs: String,
                        expecting: String,
                        file: StaticString = #file,
                        line: UInt = #line) {
    self.binaryOp(
      lhs: lhs,
      rhs: rhs,
      expecting: expecting,
      op: { $0 ^ $1 },
      inoutOp: { $0 ^= $1 },
      file: file,
      line: line
    )
  }

  internal typealias BinaryOperation = (BigInt, BigInt) -> BigInt
  internal typealias InoutBinaryOperation = (inout BigInt, BigInt) -> Void

  private func binaryOp(lhs lhsString: String,
                        rhs rhsString: String,
                        expecting expectedString: String,
                        op: BinaryOperation,
                        inoutOp: InoutBinaryOperation,
                        file: StaticString,
                        line: UInt) {
    // 'lhsBeforeInout' to later check if 'inout' did not modify original
    guard let lhs = self.create(string: lhsString, radix: 10),
          let lhsBeforeInout = self.create(string: lhsString, radix: 10) else {
      XCTFail("Unable to parse lhs", file: file, line: line)
      return
    }

    guard let rhs = self.create(string: rhsString, radix: 10) else {
      XCTFail("Unable to parse rhs", file: file, line: line)
      return
    }

    guard let expected = self.create(string: expectedString, radix: 10) else {
      XCTFail("Unable to parse expected", file: file, line: line)
      return
    }

    // Check 'standard' op
    let result = op(lhs, rhs)
    XCTAssertEqual(result, expected, file: file, line: line)

    // Check 'inout' op
    var inoutLhs = lhs
    inoutOp(&inoutLhs, rhs)
    XCTAssertEqual(inoutLhs, expected, "INOUT!!1", file: file, line: line)

    // Make sure that 'inout' did not modify original
    let inoutMsg = "Inout did modify shared/original value"
    XCTAssertEqual(lhs, lhsBeforeInout, inoutMsg, file: file, line: line)
  }

  // MARK: - Div mod

  internal func divModTest(lhs lhsString: String,
                           rhs rhsString: String,
                           div divString: String,
                           mod modString: String,
                           file: StaticString = #file,
                           line: UInt = #line) {
    guard let lhs = self.create(string: lhsString, radix: 10) else {
      XCTFail("Unable to parse lhs", file: file, line: line)
      return
    }

    guard let rhs = self.create(string: rhsString, radix: 10) else {
      XCTFail("Unable to parse rhs", file: file, line: line)
      return
    }

    guard let div = self.create(string: divString, radix: 10) else {
      XCTFail("Unable to parse div", file: file, line: line)
      return
    }

    guard let mod = self.create(string: modString, radix: 10) else {
      XCTFail("Unable to parse mod", file: file, line: line)
      return
    }

    let result = lhs.quotientAndRemainder(dividingBy: rhs)
    XCTAssertEqual(result.quotient, div, "div", file: file, line: line)
    XCTAssertEqual(result.remainder, mod, "mod", file: file, line: line)
  }

  // MARK: - Power

  internal func powerTest(base baseString: String,
                          exponent exponentInt: Int,
                          expecting expectedString: String,
                          file: StaticString = #file,
                          line: UInt = #line) {
    guard let base = self.create(string: baseString, radix: 10) else {
      XCTFail("Unable to parse lhs", file: file, line: line)
      return
    }

    guard let expected = self.create(string: expectedString, radix: 10) else {
      XCTFail("Unable to parse expected", file: file, line: line)
      return
    }

    let exp = BigInt(exponentInt)
    let result = base.power(exponent: exp)
    XCTAssertEqual(result, expected, file: file, line: line)
  }

  // MARK: - Shifts

  internal func shiftLeftTest(value: String,
                              count: Int,
                              expecting: String,
                              file: StaticString = #file,
                              line: UInt = #line) {
    self.shiftOp(
      value: value,
      count: count,
      expecting: expecting,
      op: { $0 << $1 },
      inoutOp: { $0 <<= $1 },
      file: file,
      line: line
    )
  }

  internal func shiftRightTest(value: String,
                               count: Int,
                               expecting: String,
                               file: StaticString = #file,
                               line: UInt = #line) {
    self.shiftOp(
      value: value,
      count: count,
      expecting: expecting,
      op: { $0 >> $1 },
      inoutOp: { $0 >>= $1 },
      file: file,
      line: line
    )
  }

  internal typealias ShiftOperation = (BigInt, BigInt) -> BigInt
  internal typealias InoutShiftOperation = (inout BigInt, BigInt) -> Void

  private func shiftOp(value valueString: String,
                       count countInt: Int,
                       expecting expectedString: String,
                       op: ShiftOperation,
                       inoutOp: InoutShiftOperation,
                       file: StaticString,
                       line: UInt) {

    // 'valueBeforeInout' to later check if 'inout' did not modify original
    guard let value = self.create(string: valueString, radix: 10),
          let valueBeforeInout = self.create(string: valueString, radix: 10) else {
      XCTFail("Unable to parse lhs", file: file, line: line)
      return
    }

    let count = BigInt(countInt)

    guard let expected = self.create(string: expectedString, radix: 10) else {
      XCTFail("Unable to parse expected", file: file, line: line)
      return
    }

    // Check 'standard' op
    let result = op(value, count)
    XCTAssertEqual(result, expected, file: file, line: line)

    // Check 'inout' op
    var inoutValue = value
    inoutOp(&inoutValue, count)
    XCTAssertEqual(inoutValue, expected, "INOUT!!1", file: file, line: line)

    // Make sure that 'inout' did not modify original
    let inoutMsg = "Inout did modify shared/original value"
    XCTAssertEqual(value, valueBeforeInout, inoutMsg, file: file, line: line)
  }

  // MARK: - Helpers

  /// Abstraction over `BigInt.init(_:radix:)`.
  private func create(string: String, radix: Int) -> BigInt? {
    return BigInt(string, radix: radix)
  }
}
