#if !canImport(ObjectiveC)
import XCTest

extension NoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoTests = [
        ("test_empty", test_empty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NoTests.__allTests__NoTests),
    ]
}
#endif
