import VioletCore

internal var loc0 = getLocation(0)
internal var loc1 = getLocation(1)
internal var loc2 = getLocation(2)
internal var loc3 = getLocation(3)
internal var loc4 = getLocation(4)
internal var loc5 = getLocation(5)
internal var loc6 = getLocation(6)
internal var loc7 = getLocation(7)
internal var loc8 = getLocation(8)
internal var loc9 = getLocation(9)
internal var loc10 = getLocation(10)
internal var loc11 = getLocation(11)
internal var loc12 = getLocation(12)
internal var loc13 = getLocation(13)
internal var loc14 = getLocation(14)
internal var loc15 = getLocation(15)
internal var loc16 = getLocation(16)
internal var loc17 = getLocation(17)
internal var loc18 = getLocation(18)
internal var loc19 = getLocation(19)
internal var loc20 = getLocation(20)
internal var loc21 = getLocation(21)
internal var loc22 = getLocation(22)
internal var loc23 = getLocation(23)
internal var loc24 = getLocation(24)
internal var loc25 = getLocation(25)
internal var loc26 = getLocation(26)
internal var loc27 = getLocation(27)
internal var loc28 = getLocation(28)
internal var loc29 = getLocation(29)
internal var loc30 = getLocation(30)
internal var loc31 = getLocation(31)

private func getLocation(_ n: UInt32) -> SourceLocation {
  let line = SourceLine(n)
  let column = SourceColumn((n % 2) * 5 + line) // some random
  return SourceLocation(line: line, column: column)
}
