import Foundation

// swiftlint:disable force_try
// swiftlint:disable force_unwrapping

public class EmitterBase {

  private let input: URL
  private let output: URL
  private let outputHandle: FileHandle

  public init(letItGo input: URL, output: URL) {
    self.input = input
    self.output = output
    self.outputHandle = try! FileHandle(forWritingTo: output)
  }

  deinit {
    self.outputHandle.closeFile()
  }

  public func write(_ s: String = "") {
    let line = s + "\n"
    let data = line.data(using: .utf8)!
    self.outputHandle.write(data)
  }

  public func writeHeader(command: String) {
    let filename = self.input.lastPathComponent

    self.write("""
      // This file was auto-generated by Elsa from '\(filename)'
      // using '\(command)' command.
      // DO NOT EDIT!

      """)
  }
}
