import Foundation

public class EmitterBase {

  private let file: URL
  private let handle: FileHandle

  public init(for file: URL) {
    self.file = file
    self.handle = try! FileHandle(forWritingTo: file)
  }

  deinit {
    self.handle.closeFile()
  }

  public func write(_ s: String = "") {
    let line = s + "\n"
    let data = line.data(using: .utf8)!
    self.handle.write(data)
  }

  public func writeHeader(command: String) {
    let filename = self.file.lastPathComponent

    self.write("""
      // This file was auto-generated by Elsa from '\(filename)'
      // using '\(command)' command.
      // DO NOT EDIT!

      """)
  }
}
