import Foundation

// swiftlint:disable force_unwrapping

public class EmitterBase {

  private let input: URL
  private let output: URL
  private let outputHandle: FileHandle

  public init(letItGo input: URL, output: URL) throws {
    self.input = input
    self.output = output

    if FileManager.default.fileExists(atPath: output.path) {
      try FileManager.default.removeItem(atPath: output.path)
    }
    _ = FileManager.default.createFile(atPath: output.path, contents: nil)

    self.outputHandle = try FileHandle(forWritingTo: output)
  }

  // We don't have to close file, because Swift will do that for us
  // deinit { self.outputHandle.closeFile() }

  public func write(_ s: String = "") {
    let line = s + "\n"
    let data = line.data(using: .utf8)!
    self.outputHandle.write(data)
  }

  public func writeHeader(command: String) {
    let filename = self.input.lastPathComponent

    self.write("""
      // This file was auto-generated by Elsa from '\(filename)'
      // using '\(command)' command.
      // DO NOT EDIT!

      """)
  }
}
