data = [
# name: base: doc
('BaseException', 'Object', "Common base class for all exceptions"),
  ('SystemExit', 'BaseException', "Request to exit from the interpreter."),
  ('KeyboardInterrupt', 'BaseException', "Program interrupted by user."),
  ('GeneratorExit', 'BaseException', "Request that a generator exit."),
  ('Exception', 'BaseException', "Common base class for all non-exit exceptions."),
    ('StopIteration', 'Exception', "Signal the end from iterator.__next__()."),
    ('StopAsyncIteration', 'Exception', "Signal the end from iterator.__anext__()."),
    ('ArithmeticError', 'Exception', "Base class for arithmetic errors."),
      ('FloatingPointError', 'ArithmeticError', "Floating point operation failed."),
      ('OverflowError', 'ArithmeticError', "Result too large to be represented."),
      ('ZeroDivisionError', 'ArithmeticError', "Second argument to a division or modulo operation was zero."),
    ('AssertionError', 'Exception', "Assertion failed."),
    ('AttributeError', 'Exception', "Attribute not found."),
    ('BufferError', 'Exception', "Buffer error."),
    ('EOFError', 'Exception', "Read beyond end of file."),
    ('ImportError', 'Exception', "Import can't find module, or can't find name in module."),
      ('ModuleNotFoundError', 'ImportError', "Module not found."),
    ('LookupError', 'Exception', "Base class for lookup errors."),
      ('IndexError', 'LookupError', "Sequence index out of range."),
      ('KeyError', 'LookupError', "Mapping key not found."),
    ('MemoryError', 'Exception', "Out of memory."),
    ('NameError', 'Exception', "Name not found globally."),
      ('UnboundLocalError', 'NameError', "Local name referenced but not bound to a value."),
    ('OSError', 'Exception', "Base class for I/O related errors."),
      ('BlockingIOError', 'OSError', "I/O operation would block."),
      ('ChildProcessError', 'OSError', "Child process error."),
      ('ConnectionError', 'OSError', "Connection error."),
        ('BrokenPipeError', 'ConnectionError', "Broken pipe."),
        ('ConnectionAbortedError', 'ConnectionError', "Connection aborted."),
        ('ConnectionRefusedError', 'ConnectionError', "Connection refused."),
        ('ConnectionResetError', 'ConnectionError', "Connection reset."),
      ('FileExistsError', 'OSError', "File already exists."),
      ('FileNotFoundError', 'OSError', "File not found."),
      ('InterruptedError', 'OSError', "Interrupted by signal."),
      ('IsADirectoryError', 'OSError', "Operation doesn't work on directories."),
      ('NotADirectoryError', 'OSError', "Operation only works on directories."),
      ('PermissionError', 'OSError', "Not enough permissions."),
      ('ProcessLookupError', 'OSError', "Process not found."),
      ('TimeoutError', 'OSError', "Timeout expired."),
    ('ReferenceError', 'Exception', "Weak ref proxy used after referent went away."),
    ('RuntimeError', 'Exception', "Unspecified run-time error."),
      ('NotImplementedError', 'RuntimeError', "Method or function hasn't been implemented yet."),
      ('RecursionError', 'RuntimeError', "Recursion limit exceeded."),
    ('SyntaxError', 'Exception', "Invalid syntax."),
      ('IndentationError', 'SyntaxError', "Improper indentation."),
        ('TabError', 'IndentationError', "Improper mixture of spaces and tabs."),
    ('SystemError', 'Exception', "Internal error in the Python interpreter.\n\nPlease report this to the Python maintainer, along with the traceback,\nthe Python version, and the hardware/OS platform and version."),
    ('TypeError', 'Exception', "Inappropriate argument type."),
    ('ValueError', 'Exception', "Inappropriate argument value (of correct type)."),
      ('UnicodeError', 'ValueError', "Unicode related error."),
        ('UnicodeDecodeError', 'UnicodeError', "Unicode decoding error."),
        ('UnicodeEncodeError', 'UnicodeError', "Unicode encoding error."),
        ('UnicodeTranslateError', 'UnicodeError', "Unicode translation error."),
    ('Warning', 'Exception', "Base class for warning categories."),
      ('DeprecationWarning', 'Warning', "Base class for warnings about deprecated features."),
      ('PendingDeprecationWarning', 'Warning', "Base class for warnings about features which will be deprecated\nin the future."),
      ('RuntimeWarning', 'Warning', "Base class for warnings about dubious runtime behavior."),
      ('SyntaxWarning', 'Warning', "Base class for warnings about dubious syntax."),
      ('UserWarning', 'Warning', "Base class for warnings generated by user code."),
      ('FutureWarning', 'Warning', "Base class for warnings about constructs that will change semantically\nin the future."),
      ('ImportWarning', 'Warning', "Base class for warnings about probable mistakes in module imports"),
      ('UnicodeWarning', 'Warning', "Base class for warnings about Unicode related problems, mostly\nrelated to conversion problems."),
      ('BytesWarning', 'Warning', "Base class for warnings about bytes and buffer related problems, mostly\nrelated to conversion from str or comparing to str."),
      ('ResourceWarning', 'Warning', "Base class for warnings about resource usage."),
]

def is_final(name):
  'If there exists any exception with us as base then we are not final'

  for _, base, __ in data:
    if base == name:
      return False

  return True

def print_class(name, base, doc):
  type_owner = 'warningTypes' if 'Warning' in name else 'errorTypes'
  type_variable = name[0].lower() + name[1:]

  sourcery_type = 'pywarningtype' if 'Warning' in name else 'pyerrortype'
  final = 'final ' if is_final(name) else ''
  doc = doc.replace('\n', ' " +\n"')

  print(f'// sourcery: {sourcery_type} = {name}')
  print(f'internal {final}class Py{name}: Py{base} {{')
  print()
  print('  override internal class var doc: String {')
  print(f'    return "{doc}"')
  print('  }')
  print()
  print('  override internal func initType(from context: PyContext) {')
  print(f'    self.setType(to: context.builtins.{type_owner}.{type_variable})')
  print('  }')
  print()
  print('  // sourcery: pyproperty = __class__')
  print('  override internal func getClass() -> PyType {')
  print('    return self.type')
  print('  }')
  print()
  print('  // sourcery: pyproperty = __dict__')
  print('  override internal func dict() -> Attributes {')
  print('    return self._attributes')
  print('  }')
  print('}')
  print()

def print_builtin_property(name, base):
  type_variable = name[0].lower() + name[1:]
  print(f'public let {type_variable}: PyType')

def print_builtin_assign(name, base):
  type_variable = name[0].lower() + name[1:]
  type_variable_base = base[0].lower() + base[1:]
  print(f'self.{type_variable} = PyType.{type_variable}(context, type: types.type, base: self.{type_variable_base})')

def print_cast_self(name):
  print(f'internal static func selfAsPy{name}(_ value: PyObject) -> Py{name} {{')
  print(f'  return value as! Py{name}')
  print('}')
  print()

for name, base, doc in data:
  # print_class(name, base, doc)
  # print_builtin_property(name, base)
  # print_builtin_assign(name, base)
  print_cast_self(name)


# def print_doc(exception):
#   doc = exception.__doc__.replace('\n', '\\n')
#   print(f'{exception.__name__}: {doc}')

# print_doc(BaseException)
# print_doc(SystemExit)
# print_doc(KeyboardInterrupt)
# print_doc(GeneratorExit)
# print_doc(Exception)
# print_doc(StopIteration)
# print_doc(StopAsyncIteration)
# print_doc(ArithmeticError)
# print_doc(FloatingPointError)
# print_doc(OverflowError)
# print_doc(ZeroDivisionError)
# print_doc(AssertionError)
# print_doc(AttributeError)
# print_doc(BufferError)
# print_doc(EOFError)
# print_doc(ImportError)
# print_doc(ModuleNotFoundError)
# print_doc(LookupError)
# print_doc(IndexError)
# print_doc(KeyError)
# print_doc(MemoryError)
# print_doc(NameError)
# print_doc(UnboundLocalError)
# print_doc(OSError)
# print_doc(BlockingIOError)
# print_doc(ChildProcessError)
# print_doc(ConnectionError)
# print_doc(BrokenPipeError)
# print_doc(ConnectionAbortedError)
# print_doc(ConnectionRefusedError)
# print_doc(ConnectionResetError)
# print_doc(FileExistsError)
# print_doc(FileNotFoundError)
# print_doc(InterruptedError)
# print_doc(IsADirectoryError)
# print_doc(NotADirectoryError)
# print_doc(PermissionError)
# print_doc(ProcessLookupError)
# print_doc(TimeoutError)
# print_doc(ReferenceError)
# print_doc(RuntimeError)
# print_doc(NotImplementedError)
# print_doc(RecursionError)
# print_doc(SyntaxError)
# print_doc(IndentationError)
# print_doc(TabError)
# print_doc(SystemError)
# print_doc(TypeError)
# print_doc(ValueError)
# print_doc(UnicodeError)
# print_doc(UnicodeDecodeError)
# print_doc(UnicodeEncodeError)
# print_doc(UnicodeTranslateError)
# print_doc(Warning)
# print_doc(DeprecationWarning)
# print_doc(PendingDeprecationWarning)
# print_doc(RuntimeWarning)
# print_doc(SyntaxWarning)
# print_doc(UserWarning)
# print_doc(FutureWarning)
# print_doc(ImportWarning)
# print_doc(UnicodeWarning)
# print_doc(BytesWarning)
# print_doc(ResourceWarning)
