#if !canImport(ObjectiveC)
import XCTest

extension JoinTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JoinTests = [
        ("test_join", test_join),
    ]
}

extension NameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NameTests = [
        ("test_addExt", test_addExt),
        ("test_basename", test_basename),
        ("test_basenameWithoutExt", test_basenameWithoutExt),
        ("test_dirname", test_dirname),
        ("test_extname", test_extname),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JoinTests.__allTests__JoinTests),
        testCase(NameTests.__allTests__NameTests),
    ]
}
#endif
